export const qryFeatures = groq`
  *[_type == 'features'][]{
    _id,
      title,
      subTitle,
      body,
      layout,
      featureList[]->{
        title,
        summary,
        icon{
          provider,
          name,
          'colour':iconColour.hex
        },
      image{
        'url':asset->url,
        'assetId':asset->_id
      },
      },
      cta{
        title,
        linkType,
        internalLink{
          'link':reference->{
            'slug':slug.current
          }
        },
        externalLink{
          url
        },
        'phone':{
          'number':phoneNumber->number,
          'label':phoneNumber->label
        },
        externalVideo{
          url
        }
      },
      image{
        'url':asset->url,
        'assetId':asset->_id
      },
  }
`;

export const qryFeaturesById = groq`
  *[_type == 'features' && _id == $id][0]{
    _id,
      title,
      subTitle,
      body,
      layout,
      featureList[]->{
        title,
        summary,
        icon{
          provider,
          name,
          'colour':iconColour.hex
        },
      image{
        'url':asset->url,
        'assetId':asset->_id
      },
      },
      cta{
        title,
        linkType,
        internalLink{
          'link':reference->{
            'slug':slug.current
          }
        },
        externalLink{
          url
        },
        'phone':{
          'number':phoneNumber->number,
          'label':phoneNumber->label
        },
        externalVideo{
          url
        }
      },
      image{
        'url':asset->url,
        'assetId':asset->_id
      },
  }
`;
