export const qrySiteSettings = groq`
*[_type == 'settings'][0]{
  siteOwner,
  title,
  'logoUrl':logo.asset->url,
  'image':image.asset->url,
  description,
  'email':primaryLocation->email,
  'address':primaryLocation->address,
  'addressExt':primaryLocation->addressExt,
  'city':primaryLocation->city,
  'postcode':primaryLocation->postcode,
  'country':primaryLocation->country,
  primaryLocation->{
    'lat':mapLocation.lat,
    'lng':mapLocation.lng,
    phoneNumbers[]{
      number,
      label,
    },
    socialConnections[]{
      _key,
      _type,
      title,
      'userUrl':url+username
    }
  }
  }
`;

export const qrySiteNavigation = groq`
{
  "mainNav":*[_type=="navigation" && _id == "mainNavigation"][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        'slug':reference->slug.current,
        'title':reference->title,
        reference->{
          _id
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  },
  "footerNav":*[_type=="navigation" && _id == "footerNavigation"][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        'slug':reference->slug.current,
        'title':reference->title,
        'id':reference->_id,
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  },
  "otherNav":*[_type=="navigation" && _id != 'mainNavigation' && _id != 'footerNavigation'][0]{
    _id,
    name,
    navigationLinks[]{
      _key,
      name,
      linkType,
      externalLink{
        _type,
        newWindow,
        url
      },
      internalLink{
        _type,
        reference->{
          _id,
          'slug':slug.current,
          title,
        }
      },
      anchorLink{
        _type,
        anchor,
        page->{
          _id,
        title,
        'slug':slug.current
        }
      }
    }
  }
}
`;

export const qryPage = groq`
  *[_type == 'page' && slug.current==$slug && isActive][0]{
    title,
    isActive,
    'slug':slug.current,
    'image':image.asset->url,
    body,
    _id,
    sections[]->{
      ...
    }
  }
`;

export const qryContactPage = groq`
  *[_type == 'contactpage'][0]{
    _id,
    title,
    content,
    'slug':slug.current,
    'image':image.asset->url,
    sections[]->{...}
  }
`;
